Add `--stdio` flag
shwestrick/smlfmt pull request #75
Opened 2023-01-12 03:25 UTC by azdavis

This would let Millet call `smlfmt`: https://github.com/azdavis/millet/commit/dcfa08d0b92e4c68c23a0288536e058f7674db55

2023-01-12 15:21 UTC, shwestrick requested changes
This is great, nice work! Just a few small things I think we should change first, and then I'm happy to merge.

2023-01-12 15:21 UTC, shwestrick commented on src/smlfmt.sml
> +      val parserOutput = Parser.parse allows source
If there is a parse error, this won't show any feedback to the user. We can do this instead to get an appropriate error message:

```sml
val parserOutput = Parser.parse allows source
                   handle exn => handleLexOrParseError exn
```

2023-01-12 15:21 UTC, shwestrick commented on src/smlfmt.sml
> +      print "\n"
It would be nice to use `TCS.print` here, to have syntax highlighting if printing to a terminal.

```sml
let
  ...
  val prettied = mkSMLPrettied parserOutput
in
  TCS.print prettied;
  print "\n"
end
```

It automatically detects whether or not `stdout` is a terminal to figure out if it should print colors.

So then for example `echo "val x = 5" | smlfmt --stdio` will print with syntax highlighting to the terminal, but `echo "val x = 5" | smlfmt --stdio > foo.sml` will not write colors into `foo.sml`.

2023-01-12 15:21 UTC, shwestrick commented on src/base/Source.sml
> +      val contents = Seq.fromList (String.explode s)
For really large stdin this might be slow + memory hungry?

Could we change it to this instead?
```sml
val contents =
  Seq.tabulate (fn i => String.sub (s, i)) (String.size s)
```

2023-01-12 15:23 UTC, shwestrick commented on src/smlfmt.sml
> +      print "\n"
I'm hoping this will work correctly when plugging into Millet. If the colors are messing things up though, we could add an explicit `--no-colors` flag or something.

2023-01-12 18:33 UTC, azdavis commented on src/smlfmt.sml
> +      print "\n"
this does work with millet since stdout is not a terminal, so colors are off

2023-01-13 00:43 UTC, shwestrick approved these changes

2023-01-13 00:43 UTC, merged